version: '3.6'
services:
  bookstore-api:
    build: .
    image: bookstore-api
    container_name: bookstore-api
    ports:
      - 8080:8080
    environment:
      - DATABASE_CONNECTION_STRING=jdbc:postgresql://postgres.service/bookstore
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    links:
      - postgres:postgres.service
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-bookstore-api:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres