spring:
  flyway:
    enabled: true
  datasource:
    url: ${DATABASE_CONNECTION_STRING:jdbc:postgresql://localhost:5432/bookstore}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: false
    open-in-view: false
server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: info
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus
elasticsearch:
  url: ${ELASTICSEARCH_URL:http://localhost:9200}