apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: '9200'
      port: 9200
      targetPort: 9200
      nodePort: 30953
    - protocol: TCP
      name: '9300'
      port: 9300
      targetPort: 9300
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.2
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
