kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30950
        hostPort: 8080
      - containerPort: 30951
        hostPort: 9090
      - containerPort: 30952
        hostPort: 5601
      - containerPort: 30953
        hostPort: 9200
      - containerPort: 31000
        hostPort: 3000
      - containerPort: 32000
        hostPort: 8002
